[package]
name = "comvis_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.74.2"
imageproc = {version = "0.23.0",features = ["display-window"]}
image = "0.24.5"
winit = "0.27.5"
